// Mocks generated by Mockito 5.4.6 from annotations
// in ika_smansara/test/features/forum/data/repositories/forum_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:ika_smansara/features/forum/data/datasources/forum_remote_data_source.dart'
    as _i4;
import 'package:ika_smansara/features/forum/data/models/forum_comment_model.dart'
    as _i3;
import 'package:ika_smansara/features/forum/data/models/forum_post_model.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeForumPostModel_0 extends _i1.SmartFake
    implements _i2.ForumPostModel {
  _FakeForumPostModel_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeForumCommentModel_1 extends _i1.SmartFake
    implements _i3.ForumCommentModel {
  _FakeForumCommentModel_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [ForumRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockForumRemoteDataSource extends _i1.Mock
    implements _i4.ForumRemoteDataSource {
  @override
  _i5.Future<List<_i2.ForumPostModel>> getPosts({String? category}) =>
      (super.noSuchMethod(
            Invocation.method(#getPosts, [], {#category: category}),
            returnValue: _i5.Future<List<_i2.ForumPostModel>>.value(
              <_i2.ForumPostModel>[],
            ),
            returnValueForMissingStub:
                _i5.Future<List<_i2.ForumPostModel>>.value(
                  <_i2.ForumPostModel>[],
                ),
          )
          as _i5.Future<List<_i2.ForumPostModel>>);

  @override
  _i5.Future<_i2.ForumPostModel> createPost(
    String? content,
    String? category,
    String? visibility,
    List<String>? images,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#createPost, [
              content,
              category,
              visibility,
              images,
            ]),
            returnValue: _i5.Future<_i2.ForumPostModel>.value(
              _FakeForumPostModel_0(
                this,
                Invocation.method(#createPost, [
                  content,
                  category,
                  visibility,
                  images,
                ]),
              ),
            ),
            returnValueForMissingStub: _i5.Future<_i2.ForumPostModel>.value(
              _FakeForumPostModel_0(
                this,
                Invocation.method(#createPost, [
                  content,
                  category,
                  visibility,
                  images,
                ]),
              ),
            ),
          )
          as _i5.Future<_i2.ForumPostModel>);

  @override
  _i5.Future<List<_i3.ForumCommentModel>> getComments(String? postId) =>
      (super.noSuchMethod(
            Invocation.method(#getComments, [postId]),
            returnValue: _i5.Future<List<_i3.ForumCommentModel>>.value(
              <_i3.ForumCommentModel>[],
            ),
            returnValueForMissingStub:
                _i5.Future<List<_i3.ForumCommentModel>>.value(
                  <_i3.ForumCommentModel>[],
                ),
          )
          as _i5.Future<List<_i3.ForumCommentModel>>);

  @override
  _i5.Future<_i3.ForumCommentModel> addComment(
    String? postId,
    String? content,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#addComment, [postId, content]),
            returnValue: _i5.Future<_i3.ForumCommentModel>.value(
              _FakeForumCommentModel_1(
                this,
                Invocation.method(#addComment, [postId, content]),
              ),
            ),
            returnValueForMissingStub: _i5.Future<_i3.ForumCommentModel>.value(
              _FakeForumCommentModel_1(
                this,
                Invocation.method(#addComment, [postId, content]),
              ),
            ),
          )
          as _i5.Future<_i3.ForumCommentModel>);

  @override
  _i5.Future<bool> toggleLike(String? postId) =>
      (super.noSuchMethod(
            Invocation.method(#toggleLike, [postId]),
            returnValue: _i5.Future<bool>.value(false),
            returnValueForMissingStub: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);
}
