// Mocks generated by Mockito 5.4.6 from annotations
// in ika_smansara/test/features/profile/domain/usecases/update_profile_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:ika_smansara/features/auth/domain/entities/user_entity.dart'
    as _i2;
import 'package:ika_smansara/features/profile/domain/repositories/profile_repository.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeUserEntity_0 extends _i1.SmartFake implements _i2.UserEntity {
  _FakeUserEntity_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [ProfileRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockProfileRepository extends _i1.Mock implements _i3.ProfileRepository {
  @override
  _i4.Future<_i2.UserEntity> getProfile() =>
      (super.noSuchMethod(
            Invocation.method(#getProfile, []),
            returnValue: _i4.Future<_i2.UserEntity>.value(
              _FakeUserEntity_0(this, Invocation.method(#getProfile, [])),
            ),
            returnValueForMissingStub: _i4.Future<_i2.UserEntity>.value(
              _FakeUserEntity_0(this, Invocation.method(#getProfile, [])),
            ),
          )
          as _i4.Future<_i2.UserEntity>);

  @override
  _i4.Future<_i2.UserEntity> updateProfile(_i3.ProfileUpdateParams? params) =>
      (super.noSuchMethod(
            Invocation.method(#updateProfile, [params]),
            returnValue: _i4.Future<_i2.UserEntity>.value(
              _FakeUserEntity_0(
                this,
                Invocation.method(#updateProfile, [params]),
              ),
            ),
            returnValueForMissingStub: _i4.Future<_i2.UserEntity>.value(
              _FakeUserEntity_0(
                this,
                Invocation.method(#updateProfile, [params]),
              ),
            ),
          )
          as _i4.Future<_i2.UserEntity>);
}
