// Mocks generated by Mockito 5.4.6 from annotations
// in ika_smansara/test/features/admin/users/data/repositories/admin_users_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:ika_smansara/features/admin/users/data/datasources/admin_users_remote_data_source.dart'
    as _i3;
import 'package:ika_smansara/features/auth/domain/entities/user_entity.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeUserEntity_0 extends _i1.SmartFake implements _i2.UserEntity {
  _FakeUserEntity_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [AdminUsersRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockAdminUsersRemoteDataSource extends _i1.Mock
    implements _i3.AdminUsersRemoteDataSource {
  @override
  _i4.Future<List<_i2.UserEntity>> getUsers({
    String? filter,
    int? page = 1,
    int? perPage = 20,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getUsers, [], {
              #filter: filter,
              #page: page,
              #perPage: perPage,
            }),
            returnValue: _i4.Future<List<_i2.UserEntity>>.value(
              <_i2.UserEntity>[],
            ),
            returnValueForMissingStub: _i4.Future<List<_i2.UserEntity>>.value(
              <_i2.UserEntity>[],
            ),
          )
          as _i4.Future<List<_i2.UserEntity>>);

  @override
  _i4.Future<List<_i2.UserEntity>> getPendingUsers({
    int? page = 1,
    int? perPage = 20,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getPendingUsers, [], {
              #page: page,
              #perPage: perPage,
            }),
            returnValue: _i4.Future<List<_i2.UserEntity>>.value(
              <_i2.UserEntity>[],
            ),
            returnValueForMissingStub: _i4.Future<List<_i2.UserEntity>>.value(
              <_i2.UserEntity>[],
            ),
          )
          as _i4.Future<List<_i2.UserEntity>>);

  @override
  _i4.Future<_i2.UserEntity> getUserById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getUserById, [id]),
            returnValue: _i4.Future<_i2.UserEntity>.value(
              _FakeUserEntity_0(this, Invocation.method(#getUserById, [id])),
            ),
            returnValueForMissingStub: _i4.Future<_i2.UserEntity>.value(
              _FakeUserEntity_0(this, Invocation.method(#getUserById, [id])),
            ),
          )
          as _i4.Future<_i2.UserEntity>);

  @override
  _i4.Future<void> verifyUser(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#verifyUser, [userId]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> rejectUser(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#rejectUser, [userId]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> updateUserRole(String? userId, _i2.UserRole? role) =>
      (super.noSuchMethod(
            Invocation.method(#updateUserRole, [userId, role]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> deleteUser(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteUser, [userId]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<List<_i2.UserEntity>> searchUsers(String? query) =>
      (super.noSuchMethod(
            Invocation.method(#searchUsers, [query]),
            returnValue: _i4.Future<List<_i2.UserEntity>>.value(
              <_i2.UserEntity>[],
            ),
            returnValueForMissingStub: _i4.Future<List<_i2.UserEntity>>.value(
              <_i2.UserEntity>[],
            ),
          )
          as _i4.Future<List<_i2.UserEntity>>);
}
