// Mocks generated by Mockito 5.4.6 from annotations
// in ika_smansara/test/features/forum/domain/usecases/add_forum_comment_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:ika_smansara/features/forum/domain/entities/forum_post.dart'
    as _i2;
import 'package:ika_smansara/features/forum/domain/repositories/forum_repository.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeForumPost_0 extends _i1.SmartFake implements _i2.ForumPost {
  _FakeForumPost_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeForumComment_1 extends _i1.SmartFake implements _i2.ForumComment {
  _FakeForumComment_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [ForumRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockForumRepository extends _i1.Mock implements _i3.ForumRepository {
  @override
  _i4.Future<List<_i2.ForumPost>> getPosts({String? category}) =>
      (super.noSuchMethod(
            Invocation.method(#getPosts, [], {#category: category}),
            returnValue: _i4.Future<List<_i2.ForumPost>>.value(
              <_i2.ForumPost>[],
            ),
            returnValueForMissingStub: _i4.Future<List<_i2.ForumPost>>.value(
              <_i2.ForumPost>[],
            ),
          )
          as _i4.Future<List<_i2.ForumPost>>);

  @override
  _i4.Future<_i2.ForumPost> createPost(
    String? content,
    String? category,
    String? visibility,
    List<String>? images,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#createPost, [
              content,
              category,
              visibility,
              images,
            ]),
            returnValue: _i4.Future<_i2.ForumPost>.value(
              _FakeForumPost_0(
                this,
                Invocation.method(#createPost, [
                  content,
                  category,
                  visibility,
                  images,
                ]),
              ),
            ),
            returnValueForMissingStub: _i4.Future<_i2.ForumPost>.value(
              _FakeForumPost_0(
                this,
                Invocation.method(#createPost, [
                  content,
                  category,
                  visibility,
                  images,
                ]),
              ),
            ),
          )
          as _i4.Future<_i2.ForumPost>);

  @override
  _i4.Future<List<_i2.ForumComment>> getComments(String? postId) =>
      (super.noSuchMethod(
            Invocation.method(#getComments, [postId]),
            returnValue: _i4.Future<List<_i2.ForumComment>>.value(
              <_i2.ForumComment>[],
            ),
            returnValueForMissingStub: _i4.Future<List<_i2.ForumComment>>.value(
              <_i2.ForumComment>[],
            ),
          )
          as _i4.Future<List<_i2.ForumComment>>);

  @override
  _i4.Future<_i2.ForumComment> addComment(String? postId, String? content) =>
      (super.noSuchMethod(
            Invocation.method(#addComment, [postId, content]),
            returnValue: _i4.Future<_i2.ForumComment>.value(
              _FakeForumComment_1(
                this,
                Invocation.method(#addComment, [postId, content]),
              ),
            ),
            returnValueForMissingStub: _i4.Future<_i2.ForumComment>.value(
              _FakeForumComment_1(
                this,
                Invocation.method(#addComment, [postId, content]),
              ),
            ),
          )
          as _i4.Future<_i2.ForumComment>);

  @override
  _i4.Future<bool> toggleLike(String? postId) =>
      (super.noSuchMethod(
            Invocation.method(#toggleLike, [postId]),
            returnValue: _i4.Future<bool>.value(false),
            returnValueForMissingStub: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);
}
