// Mocks generated by Mockito 5.4.6 from annotations
// in ika_smansara/test/features/settings/domain/usecases/get_printer_settings_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:ika_smansara/features/settings/domain/entities/app_settings.dart'
    as _i3;
import 'package:ika_smansara/features/settings/domain/entities/printer_settings.dart'
    as _i2;
import 'package:ika_smansara/features/settings/domain/repositories/settings_repository.dart'
    as _i4;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakePrinterSettings_0 extends _i1.SmartFake
    implements _i2.PrinterSettings {
  _FakePrinterSettings_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAppSettings_1 extends _i1.SmartFake implements _i3.AppSettings {
  _FakeAppSettings_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [SettingsRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockSettingsRepository extends _i1.Mock
    implements _i4.SettingsRepository {
  @override
  _i5.Future<_i2.PrinterSettings> getPrinterSettings() =>
      (super.noSuchMethod(
            Invocation.method(#getPrinterSettings, []),
            returnValue: _i5.Future<_i2.PrinterSettings>.value(
              _FakePrinterSettings_0(
                this,
                Invocation.method(#getPrinterSettings, []),
              ),
            ),
            returnValueForMissingStub: _i5.Future<_i2.PrinterSettings>.value(
              _FakePrinterSettings_0(
                this,
                Invocation.method(#getPrinterSettings, []),
              ),
            ),
          )
          as _i5.Future<_i2.PrinterSettings>);

  @override
  _i5.Future<void> savePrinterSettings(_i2.PrinterSettings? settings) =>
      (super.noSuchMethod(
            Invocation.method(#savePrinterSettings, [settings]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<_i3.AppSettings> getAppSettings() =>
      (super.noSuchMethod(
            Invocation.method(#getAppSettings, []),
            returnValue: _i5.Future<_i3.AppSettings>.value(
              _FakeAppSettings_1(this, Invocation.method(#getAppSettings, [])),
            ),
            returnValueForMissingStub: _i5.Future<_i3.AppSettings>.value(
              _FakeAppSettings_1(this, Invocation.method(#getAppSettings, [])),
            ),
          )
          as _i5.Future<_i3.AppSettings>);

  @override
  _i5.Future<void> saveAppSettings(_i3.AppSettings? settings) =>
      (super.noSuchMethod(
            Invocation.method(#saveAppSettings, [settings]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> clearSettings() =>
      (super.noSuchMethod(
            Invocation.method(#clearSettings, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);
}
