// Mocks generated by Mockito 5.4.6 from annotations
// in ika_smansara/test/features/events/domain/usecases/delete_booking_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;

import 'package:ika_smansara/features/events/domain/entities/event.dart' as _i2;
import 'package:ika_smansara/features/events/domain/entities/event_booking.dart'
    as _i3;
import 'package:ika_smansara/features/events/domain/entities/event_booking_ticket.dart'
    as _i4;
import 'package:ika_smansara/features/events/domain/entities/event_sponsor.dart'
    as _i9;
import 'package:ika_smansara/features/events/domain/entities/event_sub_event.dart'
    as _i8;
import 'package:ika_smansara/features/events/domain/entities/event_ticket.dart'
    as _i7;
import 'package:ika_smansara/features/events/domain/repositories/event_repository.dart'
    as _i5;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeEvent_0 extends _i1.SmartFake implements _i2.Event {
  _FakeEvent_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeEventBooking_1 extends _i1.SmartFake implements _i3.EventBooking {
  _FakeEventBooking_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeEventBookingTicket_2 extends _i1.SmartFake
    implements _i4.EventBookingTicket {
  _FakeEventBookingTicket_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [EventRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockEventRepository extends _i1.Mock implements _i5.EventRepository {
  @override
  _i6.Future<List<_i2.Event>> getEvents({
    int? page = 1,
    int? perPage = 20,
    String? category,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getEvents, [], {
              #page: page,
              #perPage: perPage,
              #category: category,
            }),
            returnValue: _i6.Future<List<_i2.Event>>.value(<_i2.Event>[]),
            returnValueForMissingStub: _i6.Future<List<_i2.Event>>.value(
              <_i2.Event>[],
            ),
          )
          as _i6.Future<List<_i2.Event>>);

  @override
  _i6.Future<_i2.Event> getEventDetail(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getEventDetail, [id]),
            returnValue: _i6.Future<_i2.Event>.value(
              _FakeEvent_0(this, Invocation.method(#getEventDetail, [id])),
            ),
            returnValueForMissingStub: _i6.Future<_i2.Event>.value(
              _FakeEvent_0(this, Invocation.method(#getEventDetail, [id])),
            ),
          )
          as _i6.Future<_i2.Event>);

  @override
  _i6.Future<List<_i7.EventTicket>> getEventTickets(String? eventId) =>
      (super.noSuchMethod(
            Invocation.method(#getEventTickets, [eventId]),
            returnValue: _i6.Future<List<_i7.EventTicket>>.value(
              <_i7.EventTicket>[],
            ),
            returnValueForMissingStub: _i6.Future<List<_i7.EventTicket>>.value(
              <_i7.EventTicket>[],
            ),
          )
          as _i6.Future<List<_i7.EventTicket>>);

  @override
  _i6.Future<List<_i8.EventSubEvent>> getEventSubEvents(String? eventId) =>
      (super.noSuchMethod(
            Invocation.method(#getEventSubEvents, [eventId]),
            returnValue: _i6.Future<List<_i8.EventSubEvent>>.value(
              <_i8.EventSubEvent>[],
            ),
            returnValueForMissingStub:
                _i6.Future<List<_i8.EventSubEvent>>.value(
                  <_i8.EventSubEvent>[],
                ),
          )
          as _i6.Future<List<_i8.EventSubEvent>>);

  @override
  _i6.Future<List<_i9.EventSponsor>> getEventSponsors(String? eventId) =>
      (super.noSuchMethod(
            Invocation.method(#getEventSponsors, [eventId]),
            returnValue: _i6.Future<List<_i9.EventSponsor>>.value(
              <_i9.EventSponsor>[],
            ),
            returnValueForMissingStub: _i6.Future<List<_i9.EventSponsor>>.value(
              <_i9.EventSponsor>[],
            ),
          )
          as _i6.Future<List<_i9.EventSponsor>>);

  @override
  _i6.Future<_i3.EventBooking> createBooking({
    required String? eventId,
    required List<Map<String, dynamic>>? metadata,
    required int? subtotal,
    required int? serviceFee,
    required int? totalPrice,
    required String? paymentMethod,
    String? registrationChannel,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createBooking, [], {
              #eventId: eventId,
              #metadata: metadata,
              #subtotal: subtotal,
              #serviceFee: serviceFee,
              #totalPrice: totalPrice,
              #paymentMethod: paymentMethod,
              #registrationChannel: registrationChannel,
            }),
            returnValue: _i6.Future<_i3.EventBooking>.value(
              _FakeEventBooking_1(
                this,
                Invocation.method(#createBooking, [], {
                  #eventId: eventId,
                  #metadata: metadata,
                  #subtotal: subtotal,
                  #serviceFee: serviceFee,
                  #totalPrice: totalPrice,
                  #paymentMethod: paymentMethod,
                  #registrationChannel: registrationChannel,
                }),
              ),
            ),
            returnValueForMissingStub: _i6.Future<_i3.EventBooking>.value(
              _FakeEventBooking_1(
                this,
                Invocation.method(#createBooking, [], {
                  #eventId: eventId,
                  #metadata: metadata,
                  #subtotal: subtotal,
                  #serviceFee: serviceFee,
                  #totalPrice: totalPrice,
                  #paymentMethod: paymentMethod,
                  #registrationChannel: registrationChannel,
                }),
              ),
            ),
          )
          as _i6.Future<_i3.EventBooking>);

  @override
  _i6.Future<List<_i3.EventBooking>> getUserBookings(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getUserBookings, [userId]),
            returnValue: _i6.Future<List<_i3.EventBooking>>.value(
              <_i3.EventBooking>[],
            ),
            returnValueForMissingStub: _i6.Future<List<_i3.EventBooking>>.value(
              <_i3.EventBooking>[],
            ),
          )
          as _i6.Future<List<_i3.EventBooking>>);

  @override
  _i6.Future<List<_i4.EventBookingTicket>> getBookingTickets(
    String? bookingId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getBookingTickets, [bookingId]),
            returnValue: _i6.Future<List<_i4.EventBookingTicket>>.value(
              <_i4.EventBookingTicket>[],
            ),
            returnValueForMissingStub:
                _i6.Future<List<_i4.EventBookingTicket>>.value(
                  <_i4.EventBookingTicket>[],
                ),
          )
          as _i6.Future<List<_i4.EventBookingTicket>>);

  @override
  _i6.Future<void> cancelBooking(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#cancelBooking, [id]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> deleteBooking(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteBooking, [id]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<_i4.EventBookingTicket> verifyTicket(String? ticketId) =>
      (super.noSuchMethod(
            Invocation.method(#verifyTicket, [ticketId]),
            returnValue: _i6.Future<_i4.EventBookingTicket>.value(
              _FakeEventBookingTicket_2(
                this,
                Invocation.method(#verifyTicket, [ticketId]),
              ),
            ),
            returnValueForMissingStub: _i6.Future<_i4.EventBookingTicket>.value(
              _FakeEventBookingTicket_2(
                this,
                Invocation.method(#verifyTicket, [ticketId]),
              ),
            ),
          )
          as _i6.Future<_i4.EventBookingTicket>);
}
