// Mocks generated by Mockito 5.4.6 from annotations
// in ika_smansara/test/features/events/data/repositories/event_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i7;

import 'package:flutter/foundation.dart' as _i3;
import 'package:ika_smansara/features/events/data/datasources/event_remote_data_source.dart'
    as _i6;
import 'package:ika_smansara/features/events/data/models/event_booking_model.dart'
    as _i4;
import 'package:ika_smansara/features/events/data/models/event_booking_ticket_model.dart'
    as _i5;
import 'package:ika_smansara/features/events/data/models/event_model.dart'
    as _i2;
import 'package:ika_smansara/features/events/data/models/event_sponsor_model.dart'
    as _i11;
import 'package:ika_smansara/features/events/data/models/event_sub_event_model.dart'
    as _i10;
import 'package:ika_smansara/features/events/data/models/event_ticket_model.dart'
    as _i8;
import 'package:ika_smansara/features/events/data/models/event_ticket_option_model.dart'
    as _i9;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeEventModel_0 extends _i1.SmartFake implements _i2.EventModel {
  _FakeEventModel_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);

  @override
  String toString({_i3.DiagnosticLevel? minLevel = _i3.DiagnosticLevel.info}) =>
      super.toString();
}

class _FakeEventBookingModel_1 extends _i1.SmartFake
    implements _i4.EventBookingModel {
  _FakeEventBookingModel_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeEventBookingTicketModel_2 extends _i1.SmartFake
    implements _i5.EventBookingTicketModel {
  _FakeEventBookingTicketModel_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [EventRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockEventRemoteDataSource extends _i1.Mock
    implements _i6.EventRemoteDataSource {
  @override
  _i7.Future<List<_i2.EventModel>> getEvents({
    int? page = 1,
    int? perPage = 20,
    String? category,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getEvents, [], {
              #page: page,
              #perPage: perPage,
              #category: category,
            }),
            returnValue: _i7.Future<List<_i2.EventModel>>.value(
              <_i2.EventModel>[],
            ),
            returnValueForMissingStub: _i7.Future<List<_i2.EventModel>>.value(
              <_i2.EventModel>[],
            ),
          )
          as _i7.Future<List<_i2.EventModel>>);

  @override
  _i7.Future<_i2.EventModel> getEventDetail(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getEventDetail, [id]),
            returnValue: _i7.Future<_i2.EventModel>.value(
              _FakeEventModel_0(this, Invocation.method(#getEventDetail, [id])),
            ),
            returnValueForMissingStub: _i7.Future<_i2.EventModel>.value(
              _FakeEventModel_0(this, Invocation.method(#getEventDetail, [id])),
            ),
          )
          as _i7.Future<_i2.EventModel>);

  @override
  _i7.Future<List<_i8.EventTicketModel>> getEventTickets(String? eventId) =>
      (super.noSuchMethod(
            Invocation.method(#getEventTickets, [eventId]),
            returnValue: _i7.Future<List<_i8.EventTicketModel>>.value(
              <_i8.EventTicketModel>[],
            ),
            returnValueForMissingStub:
                _i7.Future<List<_i8.EventTicketModel>>.value(
                  <_i8.EventTicketModel>[],
                ),
          )
          as _i7.Future<List<_i8.EventTicketModel>>);

  @override
  _i7.Future<List<_i9.EventTicketOptionModel>> getEventTicketOptions(
    String? eventId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getEventTicketOptions, [eventId]),
            returnValue: _i7.Future<List<_i9.EventTicketOptionModel>>.value(
              <_i9.EventTicketOptionModel>[],
            ),
            returnValueForMissingStub:
                _i7.Future<List<_i9.EventTicketOptionModel>>.value(
                  <_i9.EventTicketOptionModel>[],
                ),
          )
          as _i7.Future<List<_i9.EventTicketOptionModel>>);

  @override
  _i7.Future<List<_i10.EventSubEventModel>> getEventSubEvents(
    String? eventId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getEventSubEvents, [eventId]),
            returnValue: _i7.Future<List<_i10.EventSubEventModel>>.value(
              <_i10.EventSubEventModel>[],
            ),
            returnValueForMissingStub:
                _i7.Future<List<_i10.EventSubEventModel>>.value(
                  <_i10.EventSubEventModel>[],
                ),
          )
          as _i7.Future<List<_i10.EventSubEventModel>>);

  @override
  _i7.Future<List<_i11.EventSponsorModel>> getEventSponsors(String? eventId) =>
      (super.noSuchMethod(
            Invocation.method(#getEventSponsors, [eventId]),
            returnValue: _i7.Future<List<_i11.EventSponsorModel>>.value(
              <_i11.EventSponsorModel>[],
            ),
            returnValueForMissingStub:
                _i7.Future<List<_i11.EventSponsorModel>>.value(
                  <_i11.EventSponsorModel>[],
                ),
          )
          as _i7.Future<List<_i11.EventSponsorModel>>);

  @override
  _i7.Future<_i4.EventBookingModel> createBooking({
    required String? eventId,
    required List<Map<String, dynamic>>? metadata,
    required int? subtotal,
    required int? serviceFee,
    required int? totalPrice,
    required String? paymentMethod,
    String? registrationChannel,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createBooking, [], {
              #eventId: eventId,
              #metadata: metadata,
              #subtotal: subtotal,
              #serviceFee: serviceFee,
              #totalPrice: totalPrice,
              #paymentMethod: paymentMethod,
              #registrationChannel: registrationChannel,
            }),
            returnValue: _i7.Future<_i4.EventBookingModel>.value(
              _FakeEventBookingModel_1(
                this,
                Invocation.method(#createBooking, [], {
                  #eventId: eventId,
                  #metadata: metadata,
                  #subtotal: subtotal,
                  #serviceFee: serviceFee,
                  #totalPrice: totalPrice,
                  #paymentMethod: paymentMethod,
                  #registrationChannel: registrationChannel,
                }),
              ),
            ),
            returnValueForMissingStub: _i7.Future<_i4.EventBookingModel>.value(
              _FakeEventBookingModel_1(
                this,
                Invocation.method(#createBooking, [], {
                  #eventId: eventId,
                  #metadata: metadata,
                  #subtotal: subtotal,
                  #serviceFee: serviceFee,
                  #totalPrice: totalPrice,
                  #paymentMethod: paymentMethod,
                  #registrationChannel: registrationChannel,
                }),
              ),
            ),
          )
          as _i7.Future<_i4.EventBookingModel>);

  @override
  _i7.Future<List<_i4.EventBookingModel>> getUserBookings(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getUserBookings, [userId]),
            returnValue: _i7.Future<List<_i4.EventBookingModel>>.value(
              <_i4.EventBookingModel>[],
            ),
            returnValueForMissingStub:
                _i7.Future<List<_i4.EventBookingModel>>.value(
                  <_i4.EventBookingModel>[],
                ),
          )
          as _i7.Future<List<_i4.EventBookingModel>>);

  @override
  _i7.Future<List<_i5.EventBookingTicketModel>> getBookingTickets(
    String? bookingId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getBookingTickets, [bookingId]),
            returnValue: _i7.Future<List<_i5.EventBookingTicketModel>>.value(
              <_i5.EventBookingTicketModel>[],
            ),
            returnValueForMissingStub:
                _i7.Future<List<_i5.EventBookingTicketModel>>.value(
                  <_i5.EventBookingTicketModel>[],
                ),
          )
          as _i7.Future<List<_i5.EventBookingTicketModel>>);

  @override
  _i7.Future<void> cancelBooking(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#cancelBooking, [id]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> deleteBooking(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteBooking, [id]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<_i5.EventBookingTicketModel> verifyTicket(String? ticketId) =>
      (super.noSuchMethod(
            Invocation.method(#verifyTicket, [ticketId]),
            returnValue: _i7.Future<_i5.EventBookingTicketModel>.value(
              _FakeEventBookingTicketModel_2(
                this,
                Invocation.method(#verifyTicket, [ticketId]),
              ),
            ),
            returnValueForMissingStub:
                _i7.Future<_i5.EventBookingTicketModel>.value(
                  _FakeEventBookingTicketModel_2(
                    this,
                    Invocation.method(#verifyTicket, [ticketId]),
                  ),
                ),
          )
          as _i7.Future<_i5.EventBookingTicketModel>);
}
