// Mocks generated by Mockito 5.4.6 from annotations
// in ika_smansara/test/features/admin/events/data/repositories/admin_events_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:ika_smansara/features/admin/events/data/datasources/admin_events_remote_data_source.dart'
    as _i3;
import 'package:ika_smansara/features/events/domain/entities/event.dart' as _i2;
import 'package:ika_smansara/features/events/domain/entities/event_booking.dart'
    as _i5;
import 'package:ika_smansara/features/events/domain/entities/event_booking_ticket.dart'
    as _i6;
import 'package:ika_smansara/features/events/domain/entities/event_ticket.dart'
    as _i7;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeEvent_0 extends _i1.SmartFake implements _i2.Event {
  _FakeEvent_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [AdminEventsRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockAdminEventsRemoteDataSource extends _i1.Mock
    implements _i3.AdminEventsRemoteDataSource {
  @override
  _i4.Future<List<_i2.Event>> getEvents({
    String? filter,
    int? page = 1,
    int? perPage = 20,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getEvents, [], {
              #filter: filter,
              #page: page,
              #perPage: perPage,
            }),
            returnValue: _i4.Future<List<_i2.Event>>.value(<_i2.Event>[]),
            returnValueForMissingStub: _i4.Future<List<_i2.Event>>.value(
              <_i2.Event>[],
            ),
          )
          as _i4.Future<List<_i2.Event>>);

  @override
  _i4.Future<_i2.Event> getEventById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getEventById, [id]),
            returnValue: _i4.Future<_i2.Event>.value(
              _FakeEvent_0(this, Invocation.method(#getEventById, [id])),
            ),
            returnValueForMissingStub: _i4.Future<_i2.Event>.value(
              _FakeEvent_0(this, Invocation.method(#getEventById, [id])),
            ),
          )
          as _i4.Future<_i2.Event>);

  @override
  _i4.Future<_i2.Event> createEvent(Map<String, dynamic>? data) =>
      (super.noSuchMethod(
            Invocation.method(#createEvent, [data]),
            returnValue: _i4.Future<_i2.Event>.value(
              _FakeEvent_0(this, Invocation.method(#createEvent, [data])),
            ),
            returnValueForMissingStub: _i4.Future<_i2.Event>.value(
              _FakeEvent_0(this, Invocation.method(#createEvent, [data])),
            ),
          )
          as _i4.Future<_i2.Event>);

  @override
  _i4.Future<void> createEventTicket(Map<String, dynamic>? data) =>
      (super.noSuchMethod(
            Invocation.method(#createEventTicket, [data]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> updateEvent(String? eventId, Map<String, dynamic>? data) =>
      (super.noSuchMethod(
            Invocation.method(#updateEvent, [eventId, data]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> deleteEvent(String? eventId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteEvent, [eventId]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> updateEventStatus(String? eventId, String? status) =>
      (super.noSuchMethod(
            Invocation.method(#updateEventStatus, [eventId, status]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<int> getParticipantsCount(String? eventId) =>
      (super.noSuchMethod(
            Invocation.method(#getParticipantsCount, [eventId]),
            returnValue: _i4.Future<int>.value(0),
            returnValueForMissingStub: _i4.Future<int>.value(0),
          )
          as _i4.Future<int>);

  @override
  _i4.Future<Map<String, dynamic>> getEventStats(String? eventId) =>
      (super.noSuchMethod(
            Invocation.method(#getEventStats, [eventId]),
            returnValue: _i4.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
            returnValueForMissingStub: _i4.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i4.Future<Map<String, dynamic>>);

  @override
  _i4.Future<List<_i5.EventBooking>> getEventBookings(String? eventId) =>
      (super.noSuchMethod(
            Invocation.method(#getEventBookings, [eventId]),
            returnValue: _i4.Future<List<_i5.EventBooking>>.value(
              <_i5.EventBooking>[],
            ),
            returnValueForMissingStub: _i4.Future<List<_i5.EventBooking>>.value(
              <_i5.EventBooking>[],
            ),
          )
          as _i4.Future<List<_i5.EventBooking>>);

  @override
  _i4.Future<List<_i6.EventBookingTicket>> getEventBookingTickets(
    String? bookingId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getEventBookingTickets, [bookingId]),
            returnValue: _i4.Future<List<_i6.EventBookingTicket>>.value(
              <_i6.EventBookingTicket>[],
            ),
            returnValueForMissingStub:
                _i4.Future<List<_i6.EventBookingTicket>>.value(
                  <_i6.EventBookingTicket>[],
                ),
          )
          as _i4.Future<List<_i6.EventBookingTicket>>);

  @override
  _i4.Future<void> updateBookingStatus(String? bookingId, String? status) =>
      (super.noSuchMethod(
            Invocation.method(#updateBookingStatus, [bookingId, status]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> createManualBooking(Map<String, dynamic>? data) =>
      (super.noSuchMethod(
            Invocation.method(#createManualBooking, [data]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<List<_i7.EventTicket>> getEventTickets(String? eventId) =>
      (super.noSuchMethod(
            Invocation.method(#getEventTickets, [eventId]),
            returnValue: _i4.Future<List<_i7.EventTicket>>.value(
              <_i7.EventTicket>[],
            ),
            returnValueForMissingStub: _i4.Future<List<_i7.EventTicket>>.value(
              <_i7.EventTicket>[],
            ),
          )
          as _i4.Future<List<_i7.EventTicket>>);
}
