// Mocks generated by Mockito 5.4.6 from annotations
// in ika_smansara/test/features/settings/data/repositories/settings_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:ika_smansara/features/settings/data/datasources/settings_local_data_source.dart'
    as _i4;
import 'package:ika_smansara/features/settings/data/models/app_settings_model.dart'
    as _i3;
import 'package:ika_smansara/features/settings/data/models/printer_settings_model.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakePrinterSettingsModel_0 extends _i1.SmartFake
    implements _i2.PrinterSettingsModel {
  _FakePrinterSettingsModel_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAppSettingsModel_1 extends _i1.SmartFake
    implements _i3.AppSettingsModel {
  _FakeAppSettingsModel_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [SettingsLocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockSettingsLocalDataSource extends _i1.Mock
    implements _i4.SettingsLocalDataSource {
  @override
  _i5.Future<_i2.PrinterSettingsModel> getPrinterSettings() =>
      (super.noSuchMethod(
            Invocation.method(#getPrinterSettings, []),
            returnValue: _i5.Future<_i2.PrinterSettingsModel>.value(
              _FakePrinterSettingsModel_0(
                this,
                Invocation.method(#getPrinterSettings, []),
              ),
            ),
            returnValueForMissingStub:
                _i5.Future<_i2.PrinterSettingsModel>.value(
                  _FakePrinterSettingsModel_0(
                    this,
                    Invocation.method(#getPrinterSettings, []),
                  ),
                ),
          )
          as _i5.Future<_i2.PrinterSettingsModel>);

  @override
  _i5.Future<void> savePrinterSettings(_i2.PrinterSettingsModel? settings) =>
      (super.noSuchMethod(
            Invocation.method(#savePrinterSettings, [settings]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<_i3.AppSettingsModel> getAppSettings() =>
      (super.noSuchMethod(
            Invocation.method(#getAppSettings, []),
            returnValue: _i5.Future<_i3.AppSettingsModel>.value(
              _FakeAppSettingsModel_1(
                this,
                Invocation.method(#getAppSettings, []),
              ),
            ),
            returnValueForMissingStub: _i5.Future<_i3.AppSettingsModel>.value(
              _FakeAppSettingsModel_1(
                this,
                Invocation.method(#getAppSettings, []),
              ),
            ),
          )
          as _i5.Future<_i3.AppSettingsModel>);

  @override
  _i5.Future<void> saveAppSettings(_i3.AppSettingsModel? settings) =>
      (super.noSuchMethod(
            Invocation.method(#saveAppSettings, [settings]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> clear() =>
      (super.noSuchMethod(
            Invocation.method(#clear, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);
}
