// Mocks generated by Mockito 5.4.6 from annotations
// in ika_smansara/test/features/donations/domain/usecases/get_donations_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:ika_smansara/features/donations/domain/entities/donation.dart'
    as _i2;
import 'package:ika_smansara/features/donations/domain/entities/donation_transaction.dart'
    as _i3;
import 'package:ika_smansara/features/donations/domain/repositories/donation_repository.dart'
    as _i4;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeDonation_0 extends _i1.SmartFake implements _i2.Donation {
  _FakeDonation_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDonationTransaction_1 extends _i1.SmartFake
    implements _i3.DonationTransaction {
  _FakeDonationTransaction_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [DonationRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockDonationRepository extends _i1.Mock
    implements _i4.DonationRepository {
  @override
  _i5.Future<List<_i2.Donation>> getDonations() =>
      (super.noSuchMethod(
            Invocation.method(#getDonations, []),
            returnValue: _i5.Future<List<_i2.Donation>>.value(<_i2.Donation>[]),
            returnValueForMissingStub: _i5.Future<List<_i2.Donation>>.value(
              <_i2.Donation>[],
            ),
          )
          as _i5.Future<List<_i2.Donation>>);

  @override
  _i5.Future<_i2.Donation> getDonationDetail(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getDonationDetail, [id]),
            returnValue: _i5.Future<_i2.Donation>.value(
              _FakeDonation_0(
                this,
                Invocation.method(#getDonationDetail, [id]),
              ),
            ),
            returnValueForMissingStub: _i5.Future<_i2.Donation>.value(
              _FakeDonation_0(
                this,
                Invocation.method(#getDonationDetail, [id]),
              ),
            ),
          )
          as _i5.Future<_i2.Donation>);

  @override
  _i5.Future<List<_i3.DonationTransaction>> getMyDonationHistory() =>
      (super.noSuchMethod(
            Invocation.method(#getMyDonationHistory, []),
            returnValue: _i5.Future<List<_i3.DonationTransaction>>.value(
              <_i3.DonationTransaction>[],
            ),
            returnValueForMissingStub:
                _i5.Future<List<_i3.DonationTransaction>>.value(
                  <_i3.DonationTransaction>[],
                ),
          )
          as _i5.Future<List<_i3.DonationTransaction>>);

  @override
  _i5.Future<List<_i3.DonationTransaction>> getDonationTransactions(
    String? donationId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getDonationTransactions, [donationId]),
            returnValue: _i5.Future<List<_i3.DonationTransaction>>.value(
              <_i3.DonationTransaction>[],
            ),
            returnValueForMissingStub:
                _i5.Future<List<_i3.DonationTransaction>>.value(
                  <_i3.DonationTransaction>[],
                ),
          )
          as _i5.Future<List<_i3.DonationTransaction>>);

  @override
  _i5.Future<_i3.DonationTransaction> createTransaction({
    required String? donationId,
    required double? amount,
    required String? donorName,
    required bool? isAnonymous,
    String? message,
    String? paymentMethod,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createTransaction, [], {
              #donationId: donationId,
              #amount: amount,
              #donorName: donorName,
              #isAnonymous: isAnonymous,
              #message: message,
              #paymentMethod: paymentMethod,
            }),
            returnValue: _i5.Future<_i3.DonationTransaction>.value(
              _FakeDonationTransaction_1(
                this,
                Invocation.method(#createTransaction, [], {
                  #donationId: donationId,
                  #amount: amount,
                  #donorName: donorName,
                  #isAnonymous: isAnonymous,
                  #message: message,
                  #paymentMethod: paymentMethod,
                }),
              ),
            ),
            returnValueForMissingStub:
                _i5.Future<_i3.DonationTransaction>.value(
                  _FakeDonationTransaction_1(
                    this,
                    Invocation.method(#createTransaction, [], {
                      #donationId: donationId,
                      #amount: amount,
                      #donorName: donorName,
                      #isAnonymous: isAnonymous,
                      #message: message,
                      #paymentMethod: paymentMethod,
                    }),
                  ),
                ),
          )
          as _i5.Future<_i3.DonationTransaction>);
}
