// Mocks generated by Mockito 5.4.6 from annotations
// in ika_smansara/test/features/donations/data/repositories/donation_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:ika_smansara/features/donations/data/datasources/donation_remote_data_source.dart'
    as _i4;
import 'package:ika_smansara/features/donations/data/models/donation_model.dart'
    as _i2;
import 'package:ika_smansara/features/donations/data/models/donation_transaction_model.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeDonationModel_0 extends _i1.SmartFake implements _i2.DonationModel {
  _FakeDonationModel_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDonationTransactionModel_1 extends _i1.SmartFake
    implements _i3.DonationTransactionModel {
  _FakeDonationTransactionModel_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [DonationRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockDonationRemoteDataSource extends _i1.Mock
    implements _i4.DonationRemoteDataSource {
  @override
  _i5.Future<List<_i2.DonationModel>> getDonations() =>
      (super.noSuchMethod(
            Invocation.method(#getDonations, []),
            returnValue: _i5.Future<List<_i2.DonationModel>>.value(
              <_i2.DonationModel>[],
            ),
            returnValueForMissingStub:
                _i5.Future<List<_i2.DonationModel>>.value(
                  <_i2.DonationModel>[],
                ),
          )
          as _i5.Future<List<_i2.DonationModel>>);

  @override
  _i5.Future<_i2.DonationModel> getDonationDetail(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getDonationDetail, [id]),
            returnValue: _i5.Future<_i2.DonationModel>.value(
              _FakeDonationModel_0(
                this,
                Invocation.method(#getDonationDetail, [id]),
              ),
            ),
            returnValueForMissingStub: _i5.Future<_i2.DonationModel>.value(
              _FakeDonationModel_0(
                this,
                Invocation.method(#getDonationDetail, [id]),
              ),
            ),
          )
          as _i5.Future<_i2.DonationModel>);

  @override
  _i5.Future<List<_i3.DonationTransactionModel>> getMyDonationHistory() =>
      (super.noSuchMethod(
            Invocation.method(#getMyDonationHistory, []),
            returnValue: _i5.Future<List<_i3.DonationTransactionModel>>.value(
              <_i3.DonationTransactionModel>[],
            ),
            returnValueForMissingStub:
                _i5.Future<List<_i3.DonationTransactionModel>>.value(
                  <_i3.DonationTransactionModel>[],
                ),
          )
          as _i5.Future<List<_i3.DonationTransactionModel>>);

  @override
  _i5.Future<List<_i3.DonationTransactionModel>> getDonationTransactions(
    String? donationId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getDonationTransactions, [donationId]),
            returnValue: _i5.Future<List<_i3.DonationTransactionModel>>.value(
              <_i3.DonationTransactionModel>[],
            ),
            returnValueForMissingStub:
                _i5.Future<List<_i3.DonationTransactionModel>>.value(
                  <_i3.DonationTransactionModel>[],
                ),
          )
          as _i5.Future<List<_i3.DonationTransactionModel>>);

  @override
  _i5.Future<_i3.DonationTransactionModel> createTransaction({
    required String? donationId,
    required double? amount,
    required String? donorName,
    required bool? isAnonymous,
    String? message,
    String? paymentMethod,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createTransaction, [], {
              #donationId: donationId,
              #amount: amount,
              #donorName: donorName,
              #isAnonymous: isAnonymous,
              #message: message,
              #paymentMethod: paymentMethod,
            }),
            returnValue: _i5.Future<_i3.DonationTransactionModel>.value(
              _FakeDonationTransactionModel_1(
                this,
                Invocation.method(#createTransaction, [], {
                  #donationId: donationId,
                  #amount: amount,
                  #donorName: donorName,
                  #isAnonymous: isAnonymous,
                  #message: message,
                  #paymentMethod: paymentMethod,
                }),
              ),
            ),
            returnValueForMissingStub:
                _i5.Future<_i3.DonationTransactionModel>.value(
                  _FakeDonationTransactionModel_1(
                    this,
                    Invocation.method(#createTransaction, [], {
                      #donationId: donationId,
                      #amount: amount,
                      #donorName: donorName,
                      #isAnonymous: isAnonymous,
                      #message: message,
                      #paymentMethod: paymentMethod,
                    }),
                  ),
                ),
          )
          as _i5.Future<_i3.DonationTransactionModel>);
}
